# Generated by Django 3.2.5 on 2022-02-19 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0002_unresolvedquestions"),
    ]

    operations = [
        migrations.CreateModel(
            name="ChannelType",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=250)),
                ("channel_id", models.CharField(max_length=100, unique=True)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("RS", "Resource channel"),
                            ("ME", "Meme channel"),
                            ("JO", "Job offers channel"),
                            ("EM", "Emoji only channel"),
                        ],
                        max_length=2,
                    ),
                ),
            ],
        ),
    ]
